---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: panxatony
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql
      version: 9.14.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false 
  values:
    primary:
      persistence: 
        enabled: true
        storageClass: longhorn