---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: panxatony
spec:
  interval: 30m
  chart:
    spec:
      chart: wordpress
      version: 18.1.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 6
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false 
  values:
    wordpressBlogName: "Panxatony Wordpress Blog"
    wordpressUsername: admin
    wordpressPassword: nRjWLgGdW1
    wordpressFirstName: Lars
    wordpressLastName: Vonhof-Hunold
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hajimari.io/enable: "false"
      hostname: "wordpress-panxatony.${SECRET_DOMAIN}"
      tls: true
      #  - hosts:
      #      -  "wordpress-panxatony.${SECRET_DOMAIN}"
    persistence:
      enabled: true
      storageClass: longhorn
    volumePermissions:
      enabled: true
    mariadb:
      enabled: true
      auth:
        password: arUGQdLVyv
        rootPassword: ktF3nMxNXM
      volumePermissions:
        enabled:
#     primary:
#        livenessProbe:
#          enabled: true
#          initialDelaySeconds: 600
#          periodSeconds: 300
#          timeoutSeconds: 1
#        readinessProbe:
#          enabled: true
#          initialDelaySeconds: 600
#          periodSeconds: 300
#          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 90
          periodSeconds: 10
#          enabled: false
        persistence:
          enabled: true
          storageClass: longhorn
    resources:
      requests:
        cpu: 2000m
        memory: 2048M
    startupProbe:
      failureThreshold: 90
      periodSeconds: 10

#      initialDelaySeconds: 3600
#        enabled: false
#    livenessProbe:
#      initialDelaySeconds: 3600
#      enabled: true
#      failureThreshold: 20
#    readinessProbe:
#      initialDelaySeconds: 3600
#      enabled: true
#      failureThreshold: 20