ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYTlNbUgvbjdVZldtNlhu
            WXhpQk5GazF3SGhnUm5HNGg4OHg3LzNTaEZRCnFZbEZUelJKOU5YakxiMVZsakcv
            ZGpxNXFqUjc1QXdFK3VSc014dVFYdVUKLS0tIEIybWd2YmlEeFE4SzJ6N2hWYmpy
            M1RCOG91bzFTWDdsUHViclU2clZ5emsK3PVdr0ieCQZ9ChFOXNVVpxjuUHo3McMp
            MxRfWNQPQEm4wSqocQlAlh8JdrvjOrWJP/kpnmqo/sMVJMx7gxzUrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T18:58:56Z"
    mac: ENC[AES256_GCM,data:tAsHOnkUdRdeunJvEQekot0tf9OryP76zytdxqt1WU6hxKmbVO06geM3je3SD+e0SnwDANYc1KUGuSlyTnf9V6+NzEk1b7jUdx1atAQ0t8TBq/ipzonj7XipZKDFBaBalZlBnTvbiSfvKPpC1e2rkXC5ZIuQtuIY2K1mGNzwEeI=,iv:5bd1GB8sVA7RIsxEh1Ps15/a8MGAnU/7eFUTSQ+vv6U=,tag:wuaD45IXFd5HfCoIrVjkBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
