ansible_become_pass: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMHV0d1BWcTd4VldQc0pF
            V2hwL0w1OEQ4RUVmdUNBZkpaYVpEb1B5NzBRCi9INi9CYXFFNVFnN0lPeXhNazBl
            Zy80YnZ5NVRrT0tCeW00TEowM1dERVEKLS0tIDc1NnExY2JlT0J3b3ZzSjZlUG5v
            MCtkSUJ3eU9qQm9yNTRDWmNnSWdBM1kKfu1XoI32Hp0rTap21GJ5Hct0zWqSNynu
            fujdb/irFqUfReaIssxE6I0zrdwyFhG9JvuktpwTUdiN4oyaZjF/Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T10:31:24Z"
    mac: ENC[AES256_GCM,data:d38gH6wOUBm2ItU7AL42fznsL64WQ74S+1RnCPzqDHVBiuU1qIXQMoo8Mjgmsz8+nq77uyLaAnbsWBhiaj6vrDnDtf5ywhKEaTu41WiJbyHZ6r6x4+qRmG8gJtQWJZNVDeFprh4/2QCNRuf3VYoDwuzCcU60J9x8E+GFMstTBT4=,iv:6ID12SPQY3/ioo0mL6CNCbQ8yjgkQx/sUDeuCNlN+V8=,tag:Q1Fp3DSyh7ZQfnKJWez+fQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
