apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMzZJZG5yODdTZ2tQV3JI
            YmRwRlMvc1h4SXdscDNoQ29LTG5sZDFiMlQwClRiNWNscWRaSURjQk1lRElsa1NB
            OE4vMDJtNGc3SG9TcW9LUEhFWkY1Y28KLS0tIFpHaVBYdUFaaTFNSEd2QWc3aVZH
            YmV6QjcwRFpFelZMMmlOY0h4TUJ6SVUKrW+Y5wghjOM0hO/sRlswV7rwdcCY1SOB
            4crCEQ2wLV9X4owELMTVnT5G9WYKU2lNkAuT9Yw7ZWh4oTw7NRSy+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T18:59:26Z"
    mac: ENC[AES256_GCM,data:083RUWfOBHP4mbl0saJS/Ym2D2yvOum5dohGfQgxTvwJviiyhpI5bzrC42+DJqti1h6dfgyZ8pNwXF+PVE0eSHfvy5c82R8JFvP/g05cnCDIAMXSRx35YnCoAHzf/bk2ZF6AGhL39AvonEyqqvut4ax8OijlpUUELlQCATylNX8=,iv:+j61BXG4gSR6k9UhJAKqNrIrUcr9E+QLUmoR/ZtdjjE=,tag:nmF2FkN/7xoFuk7pKhW6EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
