apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2u8v+ls3UtRuEkUfLKDoa10EQlzoMNC1,iv:7cpHsYyvrezQldck2dI5z9u4r9ZXDq8gnfmz72FpcTA=,tag:vbPv1Pp84YIwrLmg9w2JIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NVVyRnJrWmpwOWtxRXha
            MXFCNnFwNjZJU29BZXZRcGw4eFNoS1VyVWg0CjV0b291cWR0MGFKWkZsWkFseGpm
            a2tKZTdtZnVsU08ySSthbGJCb3pScDAKLS0tIEtXREcxQ1QxTzBnaEpZYk1PUTVR
            UHYrZFlnSWpYbUVMUGNGdkF4QzFBa0EKFa5bmES2JDnAurwa7MZJzE8VqKnteg6x
            otBHtGKXZMvFoa0dXjScDnZKfqBiPTDeaYGzL93Ch9G50DkvLBspQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T13:15:49Z"
    mac: ENC[AES256_GCM,data:ltOv8mkeFPP5yVgMs1lP8G7jujcAzYBjJIWA9z6kSeJFvzuhCYY0bB6VWqHdhbDwte2AKQSXtOx7P4kIEcoLrl+Cg8wS3/cdTzHfquvhtiPNE/XfYHn4xsYlshxTWZzWy1VeQAE+PccoD+tsXmoYQqWqkBCvWgMI2GiiCqPWISg=,iv:77PTq35o6K3/JN9REXbh68dSOHqH24pdIl0NGhy4ylU=,tag:FQEKDlOwbiVwXYZ6QKNk+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
