apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:/hBr0KCGMafIa62NFqeSA+hG2IBmi55zznJMKzqu6NQDVAWy0hi9yA==,iv:21PJs3lnWer9vHv1ZB+Xsgl7MJhinGoh7hHXZznTYFQ=,tag:egd3+7Bs6DfEAj1dYj8+kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZXZ1MTd1TlJVZ0JqbW82
            bnNXU3luZWVKeEtVdllwWjY0TnNKQnlaRUJZClk1SVNtUFhHaFNQdmNKL1R6cVgz
            dW5ENUF2N0RkVUczK09qVGV1VHB5ZjAKLS0tIEF4clNoZ1N3d0lDSWo2Tmo3TDB6
            ZUR4ZmM5M1lLcmI4aHhwWmd6NlpNK3cKPMdhnAKETd8KZQg3WKMJ43zUxriV5uIT
            sRFuYiwtFJWrIevXFN1udFDQtwtKWRxNVmXKPCcGsVTi3A1bE3FiBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T10:31:55Z"
    mac: ENC[AES256_GCM,data:dVe0ssLQt2e9zA3nil8Ynwb8VA+eKnPP2lg72sAMlepVZaiDjz5NIWML4FQd+M7Jt5Ilam8l+Fy5bDR9/KTaBUi69MHmu65jI2Dsx92S0SoyoNCgRKO28ALRm+YNDgMToEWLEDe6V1VPjHJRQkxSt42UkYCURY5gWg7Ejfmn7c8=,iv:qV+HSs1KmvyZlQCOTqMrqxLPxRSFehgF7QQj5nLSpkE=,tag:o5XbKSGum/FO7Tnub3GWSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
