apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:TfUHxywWfbNKNIlez70NB0mc3j1+G05PzUTU8QixpUjW7M0PxxY1jQ==,iv:lhedE9ZnQ5YgutJj0a50bZoRB5/bPx1LWk8gsx5pJcA=,tag:p/6Q1GlGSeXNKuw11DZhBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL0VoZ2JuS3JGcyt1c0ZV
            UHdPNEV2cVZENmtkQXJkbHZwZnZNUFJobWdRClZidjdRcDlObVZaQVRZQ2ZoU2I1
            OFJhMWhNc1NmbGoxeVlNYXhpYi9wSzQKLS0tIEdBZStHNWtUVGluZExKbUVVK3VB
            SDJvNW9DM0R3Z0U3bFF2NVJ2VHBJTEUKX993Xa3r9fa8WwoFPQXejn4Nke5VKjfv
            is5BUeDj/gkTQj9Am1RdJgE7zJxpPWTHGI5sPso1HHfRcGon3yadPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:58:25Z"
    mac: ENC[AES256_GCM,data:pzg/zffFQs5DpZRCJKRA8zOqHqEVrEHIxI8cgmBZo752Oo2EUMxf+fJ15mLfD1Unv/6ik8g+0eWPUOgNlh0L5MVKaXfSFzgByZnNhcGNA9IWSrYhaY5YwkcdGl1ID/ODvTdJKocG3FExIZn21nH4YAbw9z82fSYL96JSrky3BHs=,iv:B/r9ZlhVw9RZ6Bku2Ycxm/Mf8wYlz0vklifZadx0M1w=,tag:aquMJyw9Ypta5exuLYCzYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
