apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:W0daVc3JbfJHOCTjYX9V/3kkUB3BOcXN0/AlllebTIKwG366zQckHgBeUIeR/vd0PbTbgPHTUa3RXXfU,iv:dgHJOyjPUz69hB/CfcEKBPJjyFTWiJxrxSiXxR7hCI8=,tag:CEUxgHJvClacQf91wlqPlw==,type:str]
    username: ENC[AES256_GCM,data:uyHt3EQ=,iv:aleqAoxavcsjtNB1HdPZubpCgNVs7+YHrs0YY6tWPTI=,tag:qm6S1dGuZHreVaGn/P19MA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScCtzUEkyWCtsTmVRZWVO
            TUJBWkI2WmhZSkd0dnl3WUx1L3k0Y3pLWlJrClpjNUpvSUFyV0ZjU1JFMzRUNWZx
            TXpHN2ZDWmV4U01wVHA5cmlhVU03K3MKLS0tIENCOGNrVGxIbWJ5Njd1N2FKeWNv
            NnREWUJTdmg5MzFtTjQ0dE1vMzBib2sKW4LbFhjbwsnqMSfMcBDZNXkSq8ZPqovA
            6oE+2cCnsuutEa5wTCzarFeoRMOlLHjGIisdD5ukCfUgttCy7mLa6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T13:15:53Z"
    mac: ENC[AES256_GCM,data:E5+w36/hA3VxEad2lW63jVFnqV2PpmNbYJiX1WL9lo/HZtAVJB0ezVHnYEttjgSA6PTOhXNb/BCW6Q//w38BGwRdGAAnOTV8FnhjNagOrw34h1StJ1r3Eq717bPNXFCstUMaIf3huIoTnELRbXl3VTKxK4YK8ZzqGYihSIbM/ro=,iv:+SJY9CyB0ooyofcyPDtyoUn1T+n48Rlv8wRu4aNDhE4=,tag:qJ9TvfL95MC2UUynOxsNlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
