apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XqOC0iRWY+/Lks6mqaOZ,iv:i2SQhPvl6P6171NTIDQiGO85zFznYyt8KeTGmXG9VmE=,tag:y8XIPoETxuD2UP4966wmag==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MeM05ptNgeZw/aY/uOC2h3sQ8k8iQ0l8hJ30a94n7hhQqxLp,iv:uEVQCA+cZmpOE9R9hyHXEfBeqzn8gRM7zoS2pPy+1Ak=,tag:/emjH61y7A8giao7V/WJMA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:MPLNXDRkoX2o5XaeiWGGCSTw4zB2PT8QQL/u,iv:Nn+FdIrIa2MTR3cxL/xoBBSTvVNN5gpRFhrTHUV8Y00=,tag:A5R68U8KJzmFeGg7jN2LBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcWR0V1IzWGpFeUlSZXll
            MkpFWGJOVVRBcVZyMzFFTFFBcjRwRHJHWlZRCmk2VHUrQys2WmJoTGhwWFFrV0xM
            Z3ZiQUt1b3J0Z3VzNkwrZlpoMGQveHcKLS0tIG5HZjRaZzQ1MlF0dTdESHpmSEFq
            SzBDbkdHU3BueFRLdjlhVkJlVk1PczAKzgM1C2lL065vSKRxTl9zaFA03JGadgLN
            1lbE7K35kDW0ErearPupvIFTtsH+dIkYaCBvECvwj/UJyq1b2wMicQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:58:25Z"
    mac: ENC[AES256_GCM,data:exj2kIGKAEZkAExppjWRxCTm1y/YIrntvgT648mMXV5vWfQ6Vm/zn7Qmk7zoGT7gZ2OS1GSMJu0ZO64hKiII+m2JDDoU4vzOIYFE5Jowq2r1JI4MW//qk+H2Aa0XBN1V8fqN8RPE80/HYeUyKLhDmGfJZf6SmC/JSI93YLt0VYc=,iv:k/FWdPSvoaMLXB9HBujbREnum78rJDirR0BHh4rlc9g=,tag:eSojdEvp9bKuAdIEGE5YSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
