apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tmiL7ZAjJAkeZn0DHPkb,iv:OY70YlV0ejqM0EGUyxt6SVBjea2Z/ti3Pp4dXXHUuXc=,tag:2OQdFeKeCpFJnDsoMgCEzg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:y8C4fVqL4U6zxZGL4rrzufodB1EVq4va11VifmUecg11MPYy,iv:nxwaO8eKnzwTBQWHXxhsGSUTA6aNnXWowgIe9DHpER8=,tag:IMkopjrfbs4ukzV5e5I3ag==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:XXqzCqDCzZjcMDfHo/CkTkO9kJpEwjQmRidZ,iv:Ma+CsmLV41x624BkSR1Je087KlmRugwFRHad3tW1A6k=,tag:yNlPib5jz16DTgigAUVjpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RWprSjBOK3JCMGE4dFJS
            NWVLY09aU1h4TDU4NWpSQ05qVFRkWFYra3pRCjJENzVZeTVCZDk2Uk5tQWpRUlNG
            UnNQRk9vclRZY0g1a2ZtN3ROWUJOMTAKLS0tIGpHTHRPUE1EVkN4L3FQOVFUeUdO
            WW1zcXB4QkJ3M1lZWXNMYXp5eWJsckUKMEyymvSopuEMATO7Knhegx87CWihabVW
            YESqiEUe5sy6Y+2QYWG4ya6ItK01/UQm4jVMQgLpj85Bi6lbsl69xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T18:59:26Z"
    mac: ENC[AES256_GCM,data:ll/muoVfU1LnOXKpNT3qb2kIt+A6bjPdOOZk589V5ELSZIrHGFxf56idAkSGhFF1a/dVPBBKEQ444I+j/JdqOyQ1U9e6X1jouRr2xQthDJjRAfxTtEgilOcpl0Q/jLr2fJACp9LL/ZFFM5Agw+zDN83MMEEDZZnC3R0ijhU0Fj0=,iv:Gea+KbYgOuozQyvEodDyQSfYqp653eThyUsUTOgtdP4=,tag:VtBOvhhpBNpSrWvbfJUKAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
