apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sE+lig0mm0w9y7+xAvgz,iv:g7rxD6GJLCtqZ9vrKMHxUwKfgS1XnzCrsthXhe+QsAI=,tag:b+8bCva9ujJFtSBi652CyA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HRVn2x3MHGXDIqHz10kZunX4uFs92l3hCkfa8s/s4MQIcfnN,iv:QuxoJbKFJa8fonblFJjInexJjMyMUc+RVtwYfB3E6v8=,tag:RCTb41NDhDC70qJmnB5CPA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2NCl4kVwDKXy1eT9ZCoX98EAOlNFDVEvdDFE,iv:xd7iP5p5r36qGUCmAYTn3r7QLfHVQwADkGiASENlA5A=,tag:XmsPcO9WJTvwpaLZUVFM6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbENJV2xXbk02Zi9XM0Rn
            YTk2NWFOTWRWYVRiOTkzeUlMMlVYRDBCelNFClhrQkxWS3ZlUEt4TTdXQXdHWGQz
            TFhaVUg4NHJ4YXhCb0ZlNmd6MllBWU0KLS0tIEpxZlNES214L0JKLzRERDBLdUov
            TVpHdGtRc3pGTDlvUmwvZFJUaWU5UTgKyNOtRuLNOzTjp1ksxLOiaioLMFBZ+X2O
            rSxM7TP0kVan8Yxvs5IJoJ9IejJDwX4pD0LA6l35gZ3g9X7nXdRj9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T10:31:54Z"
    mac: ENC[AES256_GCM,data:T/R7osZpjeA/3gRi9Nz7cQ8LzFBYyQsClIugsxXoS8F8ZxbOyg2zAQWHW11eIO1Jd5S4ufC8ifbGyROA8Q22l9xRWIex8sLwzXLWzUV+3BbWFg3pk8tSiHExsUI43GJlOQur5bTMEEFwNinvo36muaSqgTHyVtkuuWWPGaEF9ME=,iv:ELK7coEgZAvmxN0RkmChnv/CxRmLJhQb4UoIQaKR76c=,tag:foX8ylgh6b53zDsSAHUwUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
