apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:93daVsd5uLTd9m9z,iv:mqsGsRbKMxOIc0CUSjXbhvgU2i6mV1gCDpXViLO0Q+E=,tag:UoNRwhJv/L+FORABhwnuVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRXZhcE1RQTVkVmlvVUtu
            cUNTUGVrZVJ2SURmbU9zNGIxRVNXa2FTUldzCnZ5bEluTmgzNGlVSTFlbzk0cWdW
            T0x5V1ZEZXM3OGdhck5mSldPbjVUWEUKLS0tIEVNZE5aVGg4YVZ2eFpaMXpqbG1u
            M0Y1TGFMclB6eHBtS1lHcUVqQWYyV28KNRF4/FWIsAXpzlz1aM1wqJQ1zv0KDcna
            WyI0xqrj6YcGUUH+IM3Tt7yRvcD5HQGQb1X81OVSToiTq594W4tC5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T10:31:54Z"
    mac: ENC[AES256_GCM,data:FpC+6QD4nYDnV3DWfcil6T7gr+NfK5l5XYTZ+yV1Rc57FjkVXDkEbGOtGsLxP9xKZaYsqCvH8ERKIM/WW6In/KFD36Z8ExWjUJtbb76AOP8D3qRzF00I6aXDfdEOeubOba/MUQhnmP75QvC97A0PS+fqzhq/IBE+gbdyLV4IuXc=,iv:lQMHMLiTQqu2HldK9jOao9BMeRBvdTrWHX//uGirenE=,tag:pUgNVdV535oy5YsKe5WNxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
