apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UECRYbbRqPyYF/1IDcq15ufdqnwhePhdHxGRS/AxVQcM4902,iv:cYMgSLbX8DWexyzPGEr+g7RY/hloyA2GyttXfXZJlro=,tag:Us4rZbix7bs2LvWfNc9gYA==,type:str]
    credentials.json: ENC[AES256_GCM,data:+izamGbNlAe/rTj1NzgnZ4qoU+B5PA1oyVIw/DcX48HE7VOkf+3IO2iCrL9vinoTor2LOxfzGkl7+Vxa6llFLe/ldDsJhKmF5LQsd7zGMLMXRuvd94y8hllf9Wa+3tHftzW+gsAwkni3VnOZtZLubSEoGJXFmRrhv+k+xFdZPFDdarPcVzAadYXFCklHN2HLWX+m93jqOSzhw2dxkhzM1bE32BduphjPdqqNhkDNmw==,iv:DT5rLGNJM13ofe2R6UFQdUZ25ULRRZWbzD0JBcwbDQM=,tag:DfqNzaFN3MPZLUMoDrKXAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgea34nacf2sjg8ecqxh05rphmsgkev7zd4gl24tflmsll9zecgswzqc70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZXh5UGdIbGo5UytWMW5R
            dnBjNHRUY1BJRnVQeHJtOTJNVEE0L1FnMUVNClZZVUI1L0Q0K1dsemNwKzhuMkk0
            dnB6T1Z2SkJVWDZUTDJ2VXdiVkxvclkKLS0tIDU2ejFoMGhtdjFyVmZ4RVRjK0Rq
            bDdocVRlQW83dkdvaVY4dDFoNkY1YW8KVWL6EEXdfLAy3pMo7uxEHCW2BeLx80gV
            DYIz/8a2Q33FcdUL/R6IhHRq0Q27+0wgypuS+v1hl9uF40NaDzcBcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:58:26Z"
    mac: ENC[AES256_GCM,data:kvcrDCgyN/osY0A869Y3sJtGiF8ba1xzCs7MofGWlDBmqnYPBf2oDpOlZnmWAG2xNFbxGQjw4RVG3/lP27YcRQaXDgZVEu7xPJoR/0aQg53zWC2w3lFoQ1ORvW2+I06Xm3Tbqy5tFWeXS/GIwxNwWVAmSzjX+7I3JPrvMveJlDk=,iv:eqKPxNmI67VZcQNY3AUL2c93E+DthjJfg9R7G5vYBbY=,tag:xdI86uSJcJ90DMrRxFjoNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
