---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: panxatony
spec:
  interval: 30m
  chart:
    spec:
      chart: ghost
      version: 19.6.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false 
  values:
    ghostBlogTitle: "Panxatony Blog"
    ghostHost: "ghost-panxatony.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        hajimari.io/enable: "true"
      hostname: "ghost-panxatony.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      storageClass: longhorn
    volumePermissions:
      enabled: true
    mysql:
      enabled: true
      volumePermissions:
        enabled:
      primary:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        startupProbe:
          enabled: false
        persistence:
          enabled: true
          storageClass: longhorn
    resources:
      requests:
        cpu: 500m
        memory: 1024M