---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: panxatony
spec:
  interval: 30m
  chart:
    spec:
      chart: ghost
      version: 19.6.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false 
  values:
    ghostBlogTitle: "Panxatony Blog"
    ghostPassword: nRjWLgGdW1
    ghostHost: "ghost-panxatony.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hajimari.io/enable: "false"
      hostname: "ghost-panxatony.${SECRET_DOMAIN}"
      tls:
        - hosts:
            -  "ghost-panxatony.${SECRET_DOMAIN}"
    persistence:
      enabled: true
      storageClass: longhorn
    volumePermissions:
      enabled: true
    mysql:
      enabled: true
      auth:
        password: arUGQdLVyv
        rootPassword: ktF3nMxNXM
      volumePermissions:
        enabled:
      primary:
        livenessProbe:
          enabled: true
          initialDelaySeconds: 600
          periodSeconds: 300
          timeoutSeconds: 1
        readinessProbe:
          enabled: true
          initialDelaySeconds: 600
          periodSeconds: 300
          timeoutSeconds: 1
#        livenessProbe:
#          enabled: false
#        readinessProbe:
#          enabled: false
        startupProbe:
          enabled: false
        persistence:
          enabled: true
          storageClass: longhorn
    resources:
      requests:
        cpu: 500m
        memory: 1024M
    startupProbe:
        enabled: false
    livenessProbe:
      enabled: true
      failureThreshold: 20
    readinessProbe:
      enabled: true
      failureThreshold: 20